### ISSUE TITLE
readiness error

### ISSUE THREAD

**Issue by cw1427** [tamirdavid/benchmark#3]
17:45:00 [Error] Readinesshttps://**************/artifactory/api/v1/system/readiness failed
exit status 1

The benchmark api url doesn't exists on Artifactory 7.10 enterprise

**Comment by eldada** [comment]
That's right! @tamirdavid , we need to add a condition to use the old `artifactory/api/system/ping` for older versions. I don't remember the exact version. It was 7.2x.x IIRC.

**Comment by tamirdavid** [comment]
Thank you for informing me. The issue has been resolved after testing on a local Artifactory server with an older version.
```
$ ./benchmark dl --size 30 --iterations 4 --url http://xxxx --username xx --password bbb
11:19:33 [🔵Info] Validate url is an Artifactory server by sending readiness request [http://xxxx/artifactory/api/v1/system/readiness]
11:19:33 [🟠Warn] Validation through the readiness check has failed, potentially due to the use of an old Artifactory version. Attempt to validate using the system/ping.
11:19:33 [🔵Info] Validate url is an Artifactory server by sending system/ping request [http://xxxx/artifactory/api/system/ping]
```
